# Generated by Django 3.1.7 on 2025-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250410_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catefory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
