# Generated by Django 3.1.7 on 2025-04-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_catefory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catefory',
            new_name='Category',
        ),
    ]
